# Generated by Django 3.2.8 on 2021-10-20 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tag', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Tag')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Currently Active?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_token', models.CharField(max_length=200, null=True, verbose_name='Verfication Token')),
                ('reset_password_token', models.CharField(max_length=200, null=True, verbose_name='Reset Password Token')),
                ('reset_instance_token', models.CharField(max_length=200, null=True, verbose_name='Reset Instance Token')),
                ('password_reset_at', models.DateTimeField(default='2000-01-01 0:00:00+00:00', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['updated_at', '-created_at'],
            },
        ),
    ]
